const router = require("express").Router();
const controller = require("../controller/teamController");

router.get("/getAllTeams", controller.getAllTeams);
router.post("/savePlayerInfo", controller.savePlayerInfo);
router.get("/getTeamsPlayers", controller.getTeamsPlayers);
router.put("/updateTeam", controller.updateTeam);
router.post("/createTeams", controller.createTeams);
router.get("/getTeamStats", controller.getTeamStats);
router.put("/updatePlayerStats", controller.updatePlayerStats);
router.get("/getPlayerStats", controller.getPlayerStats);
router.get("/getLeagueStats", controller.getLeagueStats);
router.post("/postCollegePlayers", controller.postCollegePlayers);
router.put("/updateCollegePlayers", controller.updateCollegePlayers);
router.get("/renderPlayerProfile", controller.renderPlayerProfile);
router.get("/renderTeamProfile", controller.renderTeamProfile);
router.get("/getPlayerProfile/:id", controller.getPlayerProfile);
router.get("/getTeamProfile/:id", controller.getTeamProfile);
router.put("/loadTeamLogoColor", controller.loadTeamLogoColor);
router.get("/getTeamColors/:team", controller.getTeamColors);
router.get("/getPositionStats", controller.getPositionStats);
router.get("/getCollegePlayerProfile/:id", controller.getCollegePlayerProfile);
router.post("/createCollegeTeams", controller.createCollegeTeams);
router.get("/getCollegeTeamColors/:team", controller.getCollegeTeamColors);
router.get("/getCollegeTeamProfile/:id", controller.getCollegeTeamProfile);
router.get("/getCollegeTeamsPlayers", controller.getCollegeTeamsPlayers);
router.get("/getcLeagueStats", controller.getcLeagueStats);
router.get("/getcPlayerStats", controller.getcPlayerStats);
router.get("/getcPositionStats", controller.getcPositionStats);

module.exports = router;
